#!/bin/sh

CALLER_ID=`aws sts get-caller-identity`
if [ $? -ne 0 ]; then
    echo "Can't get caller identity"
    exit 77
fi

ACCT=`echo ${CALLER_ID} | jq -r '.Account'`
AWS_USER_ID=`echo ${CALLER_ID} | jq -r '.UserId'`

UID_PFX=`echo $AWS_USER_ID | cut -c 1-4`
case $UID_PFX in
    AIDA )
        # things look good
        ;;
    * )
        echo "Ambient credentials do not belong to an IAM user"
        exit 77
        ;;
esac

AWS_USER=`echo ${CALLER_ID} | jq -r '.Arn'`
AWS_USER=`basename $AWS_USER`

TS=`date -u +%Y%m%dT%H%M%SZ`
RSN="$AWS_USER-$TS"

AWS_MFA_SERIAL=`aws iam list-virtual-mfa-devices |\
    jq -r --arg AWS_USER $AWS_USER '.VirtualMFADevices[] |\
    select(.User.UserName == $AWS_USER).SerialNumber'`

read -n 6 -p "Token Code: " TK
echo

EPHEM=`aws sts get-session-token --serial-number $AWS_MFA_SERIAL --token-code $TK`

if [ $? != 0 ]; then
    echo
    echo "'aws sts get-session-token' failed"
    exit 75
fi

AWS_ACCESS_KEY_ID=`echo $EPHEM | jq -r '.Credentials.AccessKeyId'`
export AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=`echo $EPHEM | jq -r '.Credentials.SecretAccessKey'`
export AWS_SECRET_ACCESS_KEY
AWS_SESSION_TOKEN=`echo $EPHEM | jq -r '.Credentials.SessionToken'`
export AWS_SESSION_TOKEN
AWS_SESSION_EXPIRATION=`echo $EPHEM | jq -r '.Credentials.Expiration'`
export AWS_SESSION_EXPIRATION

exec $SHELL

