#!/bin/sh

# ROLE="radmin"

CALLER_ID=`aws sts get-caller-identity`
if [ $? -ne 0 ]; then
    echo "Can't get caller identity"
    exit 77
fi

ACCT=`echo ${CALLER_ID} | jq -r '.Account'`
USERID=`echo ${CALLER_ID} | jq -r '.UserId'`

UID_PFX=`echo $USERID | cut -c 1-4`
case $UID_PFX in
    AAGA | ACCA | AGPA | AIPA | AKIA | ANPA | ANVA | APKA | AROA | ASCA | ASIA )
        echo "Ambient credentials do not belong to an IAM user"
        exit 77
        ;;
    AIDA )
        # things look good
        ;;
    * )
        echo "unrecognized caller id: \"$USERID\""
        exit 77
        ;;
esac

read -p 'Role Name: ' ROLE
read -s -p 'token code: ' -n 6 TOKEN_CODE
echo

USER=`echo ${CALLER_ID} | jq -r '.Arn'`
USER=`basename $USER`

TS=`date -u +%Y%m%dT%H%M%SZ`
RSN="$USER-$TS"

CREDS=`aws sts assume-role \
	--role-arn arn:aws:iam::${ACCT}:role/${ROLE} \
	--role-session-name $RSN \
	--serial-number arn:aws:iam::${ACCT}:mfa/${USER} \
    --duration-seconds 28800 \
	--token-code $TOKEN_CODE`

AWS_ACCESS_KEY_ID=`echo $CREDS | jq -r '.Credentials.AccessKeyId'`
export AWS_ACCESS_KEY_ID

AWS_SECRET_ACCESS_KEY=`echo $CREDS | jq -r '.Credentials.SecretAccessKey'`
export AWS_SECRET_ACCESS_KEY

AWS_SESSION_TOKEN=`echo $CREDS | jq -r '.Credentials.SessionToken'`
export AWS_SESSION_TOKEN

exec $SHELL

