#!/bin/sh
#
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
VLAN1_IF="eth0"

VLAN=$1

if [ $# -lt 1 ]; then
	printf "usage:\t`basename $0` <vlan id>\n\te.g. `basename $0` 2 3 4\n"
	exit 23
fi
for VLAN in $*; do

	if [ "${VLAN}" = "1" ]; then
		IF="$VLAN1_IF"
	else
		IF="vlan${VLAN}"
	fi

	dhcpd \
		-cf /usr/local/etc/dhcpd-${VLAN}.conf \
		-lf /var/db/dhcpd/dhcpd-${VLAN}.leases \
		-pf /var/run/dhcpd/dhcpd-${VLAN}.pid \
		-user dhcpd -group dhcpd $IF
done

